### ISSUE TITLE
Overflowing

### ISSUE THREAD

**Issue by kush-singh-chb** [jifalops/simple_autocomplete_formfield#4]
The Suggestions cant be seen and there is a yellow and black strip...help

```dart
Expanded(
              child: SimpleAutocompleteFormField<String>(
                itemBuilder: (context, string) => Text(string),
                onSearch: (String search) async {
                  InvoiceFormData.states
                      .where((String string) => string.contains(search));
                },
                maxSuggestions: 5,
                onFieldSubmitted: (string) => _formData.state = string,
              ),
            ),
```

**Comment by jifalops** [comment]
**Update:** This is unlikely to be the solution, see the next comment below.

I don't have much to go by but I believe wrapping it in an `Expanded` is not the right approach. Try changing the `containerBuilder` parameter. The default is

```dart
containerBuilder = containerBuilder ??
            ((context, items) => Container(
                  height: 200.0,
                  child: SingleChildScrollView(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.stretch,
                      children: items,
                    ),
                  ),
                )),
```
Simply removing the `height` will make it expand vertically.

**Comment by jifalops** [comment]
A SimpleAutocompleteFormField should have an ancestor in the Widget tree that allows scrolling such as a `ListView` or `SingleChildScrollView`. I am not aware of any other work around that can be completely contained within the widget itself.
