### ISSUE TITLE
How to handle itemFromString when data is fetched from API

### ISSUE THREAD

**Issue by Sh1d0w** [jifalops/simple_autocomplete_formfield#5]
Hi,

and thanks for the great plugin. I am running into a problem, where I have SimpleAutocompleteFormField which is displaying suggestions from remote API. However if I programatically change the TextEditingController.text to a given string, there is no way to return an Object of the given class, since the `itemFromString` is not async function and expects me to return object of that class instantly, but I need to fetch them from the API?

Is there a way to do that, or am I missing something?

**Comment by jifalops** [comment]
The assumption is that any async work is done during `onSearch()`, and when `itemFromString()` is called you already have the List of items returned from onSeach(). The string then refers to one of the already fetched suggestions.

**Comment by Sh1d0w** [comment]
@jifalops That's right, but I have the following case:

I have a from with user address fields, from which the City is SimpleAutocompleteFormField that makes remote request to an API to fetch City objects with id and name.

I also have a dropdown out of the form with list of user addresses the user already have. So you can choose one of those to pre-populate the form below with the address, postcode and the city.

The problem is that when I set the controller text value programatically, the onSearch is not called (as it shouldn't be as the user is not interacting with this widget).

I have a workaround that I have wrapped the SimpleAutocompleteFormField in my custom widget that accepts list of the users saved addresses and then in `itemFromString` I filter them, but I was wondering if there is a better way to achieve this without having to do this.

If there is no better way you can close this issue, but I was wondering if SimpleAutocompleteFormField should have some mechanism to set the field value other than setting the text controller text string only, but to set the actual object, just like setting the initialValue?

Something like `autocompleteField.setValue<City>(city)`, I think this will be very useful?

**Comment by ketulrastogi** [comment]
Thank you for this awesome plugin.
is there any option in this plugin to use stream data from cloud firestore?

**Comment by jifalops** [comment]
You can use a `key` to call the widget's state's `setValue()` method.

```dart
final widgetKey = GlobalKey<FormFieldState<City>>();
...
SimpleAutocompleteFormField<City>(key: widgetKey,
...
widgetKey.currentState.setValue(value)
```
